name: WGFactions
main: com.github.pocketkid2.wgf.WGFPlugin
version: 0.1.2
api-version: 1.14
depend: [WorldGuard, Factions]
author: Pocketkid2
description: World Guard and Factions working together!
commands:
    wgfadd:
        description: Add all players in a group of a faction to a region
        usage: /wgfadd <region> <faction> <officer|member|all> [world]
        permission: wgf.add
        permisison-message: You don't have permission!
    wgfremove:
        description: Remove all players in a faction from a region
        usage: /wgfremove <region> <faction> [world]
        permission: wgf.remove
        permission-message: You don't have permission!
permissions:
    wgf.add:
        description: Allows /wgfadd
        default: op
    wgf.remove:
        description: Allows /wgfremove
        default: op
    wgf.override:
        description: Allows entitys other then the owner of a region to use /wgfremove & /wgfadd
        default: op
